import ThemeToggle from "@/components/ThemeToglle";
import "./globals.css";
import "../components/css/global.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../app/css/pages.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config, icon } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Smart Academy",
  // description: "Generated by create next app",
  icons: "/smart-logo.svg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          className="d-flex align-items-center m-3 rounded-2 justify-content-center gap-1 p-2 text-white"
          style={{
            background: "var(--btns)",
            color: "#ffff !important",
            fontWeight: "300",
          }}
        >
          <p className="m-0">Free Courses 🌟 Sale Ends Soon, Get It Now</p>
          <FontAwesomeIcon icon={faArrowRight} width={20} />
        </header>
        <Navbar />
        {children}
        {/* <ThemeToggle/>   */}

        <Footer />
      </body>
    </html>
  );
}
