import ThemeToggle from "@/components/ThemeToglle";
import "./globals.css";
import "../components/css/global.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../app/css/pages.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config, icon } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/redux/Provider";
import { useSelector } from "react-redux";
import Header from "@/components/Header";

export const metadata = {
  title: "Smart Academy",
  // description: "Generated by create next app",
  icons: "/smart-logo.svg",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Providers>

          <Header/>
          <Navbar />
          {children}
          {/* <ThemeToggle/>   */}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
